// api/_bits_registry.js
// Source: SpamViking_BitsRegistry.json (141 bits)
// DO NOT hand-edit. Regenerate from SpamViking_BitsRegistry.json when the Bits Library recompiles.
// Generated: 2026-07-18

export const BITS = [
  {"id": "BIT-101", "name": "The Echo", "archetypes": "universal", "bit_type": "count", "count_label": "phrases adopted", "fuel_hooks": ["pitch_claims"], "cooldown": 3, "gear": {"pressure": {"pushing": 1.0, "extracting": 1.0}, "engagement": {"bored": 2.0, "hooked": 2.0, "stunned": 2.0}}, "phase_pref": "pitching"},
  {"id": "BIT-102", "name": "Old Saws", "archetypes": "universal", "cooldown": 3, "gear": {"pressure": {"calm": 0.5, "pushing": 1.0, "extracting": 1.0}}},
  {"id": "BIT-103", "name": "The Quotes Bit", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 1.0, "hooked": 1.0, "stunned": 0.0}}},
  {"id": "BIT-104", "name": "Malaprops", "archetypes": "universal", "bit_type": "count", "count_label": "substitutions", "cooldown": 2, "gear": {"pressure": {"calm": 1.0, "pushing": 1.0, "extracting": 1.0}}},
  {"id": "BIT-105", "name": "The Eggcorn Bit", "archetypes": "universal", "bit_type": "count", "count_label": "eggcorns", "cooldown": 3, "gear": {"pressure": {"calm": 1.0, "pushing": 1.0, "extracting": 1.0}}},
  {"id": "BIT-106", "name": "The Metric Bit", "archetypes": "universal", "cooldown": 4, "gear": {"pressure": {"pushing": 1.0, "extracting": 2.0}}},
  {"id": "BIT-107", "name": "Metric Vs. Imperial", "archetypes": "universal", "cooldown": 4, "gear": {"pressure": {"pushing": 1.0, "extracting": 2.0}}},
  {"id": "BIT-108", "name": "The Acronym Bit", "archetypes": "universal", "cooldown": 3, "gear": {"pressure": {"calm": 1.0, "pushing": 2.0, "extracting": 1.0}}},
  {"id": "BIT-109", "name": "The Buzzword Lag", "archetypes": "universal", "cooldown": 3, "gear": {"engagement": {"bored": 2.0, "hooked": 0.0, "stunned": -1.0}}},
  {"id": "BIT-110", "name": "The Name Pronunciation Bit", "archetypes": "universal", "cooldown": 4, "gear": {"pressure": {"calm": 1.0, "pushing": 1.0, "extracting": 0.0}}},
  {"id": "BIT-111", "name": "The Callback Bit", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 1.0, "stunned": 0.0}}},
  {"id": "BIT-112", "name": "The Pause Bit", "archetypes": "universal", "cooldown": 3, "gear": {"pressure": {"pushing": 1.0, "extracting": 2.0}}, "phase_pref": "drifting"},
  {"id": "BIT-112b", "name": "Still Going?", "archetypes": "universal", "bit_type": "count", "count_label": "overheld pauses", "cooldown": 3, "gear": {"suspicion": {"alive": 1.0, "slipping": 2.0}, "pressure": {"pushing": 1.0, "extracting": 2.0}, "engagement": {"bored": 2.0, "hooked": 2.0}}, "phase_pref": "drifting"},
  {"id": "BIT-113", "name": "The Movie Bit", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": -1.0, "hooked": 2.0, "stunned": 1.0}}},
  {"id": "BIT-114", "name": "The Movie Quote / Misquote Bit", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": -1.0, "hooked": 2.0, "stunned": 1.0}}},
  {"id": "BIT-115", "name": "The Robot Voice Bit", "archetypes": "universal", "cooldown": 5, "gear": {"suspicion": {"alive": 1.0, "slipping": 2.0, "foregone": 0.0}, "engagement": {"hooked": 1.0, "stunned": 2.0, "bored": -1.0}}},
  {"id": "BIT-116", "name": "The Name Collision Bit", "archetypes": "universal", "cooldown": 3, "gear": {"pressure": {"calm": 1.0, "pushing": 2.0, "extracting": 1.0}}},
  {"id": "BIT-117", "name": "The Lyric Bit", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 0.0, "hooked": 2.0, "stunned": 1.0}}},
  {"id": "BIT-118", "name": "The Negation Drop", "archetypes": "universal", "fuel_hooks": ["dossier_negation"], "cooldown": 6, "gear": {"pressure": {"extracting": 2.0}, "engagement": {"hooked": 2.0, "stunned": 1.0, "bored": -1.0}}, "phase_pref": "pitching"},
  {"id": "BIT-119", "name": "The Hype Spiral", "archetypes": ["crypto_investment"], "cooldown": 5, "gear": {"engagement": {"bored": -1.0, "hooked": 2.0, "stunned": 2.0}, "pressure": {"calm": 1.0, "pushing": 2.0, "extracting": 1.0}}, "phase_pref": "pitching"},
  {"id": "BIT-120", "name": "The Emotional Crescendo", "archetypes": ["crypto_investment"], "cooldown": 5, "gear": {"engagement": {"bored": -1.0, "hooked": 2.0, "stunned": 3.0}, "pressure": {"pushing": 1.0, "extracting": 2.0}}},
  {"id": "BIT-121", "name": "My Name, Actually", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0, "stunned": 1.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-122", "name": "I Get That A Lot", "archetypes": "universal", "cooldown": 6, "gear": {"engagement": {"bored": 1.0, "hooked": 1.0, "stunned": 2.0}, "suspicion": {"alive": 1.0, "slipping": 1.0}}},
  {"id": "BIT-123", "name": "The Strong Opinion", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"hooked": 2.0, "stunned": 1.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-124", "name": "The Previous Vendor", "archetypes": "universal", "cooldown": 5, "gear": {"pressure": {"pushing": 1.0, "extracting": 1.0}, "engagement": {"hooked": 2.0, "stunned": 1.0}}},
  {"id": "BIT-125", "name": "The Tangent", "archetypes": "universal", "bit_type": "count", "count_label": "tangents", "cooldown": 3, "gear": {"engagement": {"bored": 2.0, "hooked": 1.0}, "pressure": {"calm": 1.0}}},
  {"id": "BIT-126", "name": "The Aside", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-127", "name": "The Correction", "archetypes": "universal", "bit_type": "count", "count_label": "self-corrections", "cooldown": 3, "gear": {"engagement": {"bored": 1.0, "hooked": 1.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-128", "name": "The Pivot Question", "archetypes": "universal", "cooldown": 3, "gear": {"suspicion": {"slipping": 2.0, "foregone": 1.0}, "pressure": {"extracting": 2.0, "pushing": 1.0}, "engagement": {"bored": 3.0, "hooked": 1.0}}, "phase_pref": "drifting"},
  {"id": "BIT-129", "name": "The Reframe", "archetypes": "universal", "cooldown": 3, "gear": {"suspicion": {"slipping": 2.0}, "pressure": {"extracting": 2.0, "pushing": 1.0}, "engagement": {"bored": 3.0, "hooked": 1.0}}, "phase_pref": "drifting"},
  {"id": "BIT-130", "name": "How Are You", "archetypes": "universal", "bit_type": "count", "count_label": "genuine answers", "cooldown": 5, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0}, "pressure": {"calm": 2.0}}, "phase_pref": "opening"},
  {"id": "BIT-131", "name": "The Busy Escalation", "archetypes": "universal", "bit_type": "count", "count_label": "busy exchanges", "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 1.0}, "pressure": {"calm": 2.0}}, "phase_pref": "opening"},
  {"id": "BIT-132", "name": "The Expansion News", "archetypes": "universal", "cooldown": 6, "gear": {"suspicion": {"alive": 2.0, "slipping": 1.0}, "engagement": {"hooked": 2.0, "stunned": 2.0}, "pressure": {"pushing": 1.0}}, "phase_pref": "opening"},
  {"id": "BIT-133", "name": "Audio Verification", "archetypes": "universal", "bit_type": "count", "count_label": "audio checks", "cooldown": 3, "gear": {"engagement": {"bored": 2.0}, "pressure": {"calm": 2.0}}, "phase_pref": "opening"},
  {"id": "BIT-134", "name": "Six Degrees", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0}, "pressure": {"calm": 1.0}}, "phase_pref": "opening"},
  {"id": "BIT-135", "name": "The Punctuality", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0}, "pressure": {"calm": 2.0}}, "phase_pref": "opening"},
  {"id": "BIT-136", "name": "The Commute", "status": "parked", "park_reason": "superseded by BIT-326", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 1.0}, "pressure": {"calm": 1.0}}},
  {"id": "BIT-137", "name": "The History Lesson", "status": "parked", "park_reason": "superseded by BIT-327", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 2.0, "stunned": 1.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-138", "name": "The Hobby", "status": "parked", "park_reason": "superseded by BIT-328", "archetypes": "universal", "cooldown": 3, "gear": {"engagement": {"hooked": 3.0, "stunned": 2.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-139", "name": "Genealogy", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": 2.0, "hooked": 2.0}, "pressure": {"calm": 1.0}}},
  {"id": "BIT-140", "name": "The Bucket List", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"hooked": 2.0, "stunned": 1.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-141", "name": "Sports Expectations", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0}, "pressure": {"calm": 1.0}}},
  {"id": "BIT-142", "name": "Fantasy Football", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0, "stunned": 1.0}, "pressure": {"calm": 1.0}}},
  {"id": "BIT-143", "name": "The Challenge Riff", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"hooked": 2.0, "stunned": 1.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-144", "name": "Celebrity Sighting", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0, "stunned": 2.0}, "pressure": {"calm": 1.0}}},
  {"id": "BIT-145", "name": "The Sniglet", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-201", "name": "The Competitor Bit", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0, "stunned": 0.0}}},
  {"id": "BIT-202", "name": "The Foreshadowing Bit", "archetypes": "universal", "cooldown": 5, "gear": {"pressure": {"calm": 2.0, "pushing": 1.0, "extracting": 0.0}, "engagement": {"hooked": 1.0}}},
  {"id": "BIT-203", "name": "The Agenda Bit", "archetypes": "universal", "cooldown": 3, "gear": {"pressure": {"calm": 2.0, "pushing": 2.0, "extracting": 1.0}}},
  {"id": "BIT-204", "name": "The Nda Bit", "archetypes": "universal", "cooldown": 4, "gear": {"suspicion": {"slipping": 1.0}, "pressure": {"pushing": 2.0, "extracting": 2.0}}},
  {"id": "BIT-205", "name": "The Reschedule Bit", "archetypes": "universal", "cooldown": 4, "gear": {"pressure": {"pushing": 1.0, "extracting": 2.0}}},
  {"id": "BIT-206", "name": "The Document Request + Photo Bit", "archetypes": ["b2b_saas"], "cooldown": 4, "gear": {"pressure": {"pushing": 2.0, "extracting": 1.0}}},
  {"id": "BIT-207", "name": "The Tom Echo", "archetypes": "universal", "bit_type": "count", "count_label": "check-ins", "cooldown": 3, "gear": {"pressure": {"calm": 1.0, "pushing": 2.0, "extracting": 2.0}}},
  {"id": "BIT-208", "name": "The Forwarded Email Bit", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0}}},
  {"id": "BIT-209", "name": "The Previous Call Bit", "archetypes": "universal", "cooldown": 6, "gear": {"engagement": {"bored": 1.0, "hooked": 3.0}}},
  {"id": "BIT-210", "name": "Cry Poverty", "archetypes": "universal", "cooldown": 3, "gear": {"pressure": {"pushing": 1.0, "extracting": 2.0}, "engagement": {"bored": 2.0}}},
  {"id": "BIT-211", "name": "The Silence / The Pile-Up", "archetypes": "universal", "bit_type": "count", "count_label": "silences", "cooldown": 3, "gear": {"pressure": {"pushing": 2.0, "extracting": 3.0}}},
  {"id": "BIT-212", "name": "The Join", "archetypes": "universal", "cooldown": 4, "gear": {"pressure": {"calm": 1.0, "pushing": 2.0}, "engagement": {"hooked": 1.0}}},
  {"id": "BIT-213", "name": "The Accidental Joiner", "archetypes": "universal", "cooldown": 5, "gear": {"suspicion": {"slipping": -1.0, "foregone": -2.0}, "engagement": {"hooked": 2.0, "stunned": 1.0, "bored": -1.0}}},
  {"id": "BIT-214", "name": "The Two Spammers", "archetypes": "universal", "cooldown": 5, "gear": {"pressure": {"extracting": 2.0}, "engagement": {"hooked": 2.0, "stunned": 1.0}}},
  {"id": "BIT-215", "name": "No You Go", "archetypes": "universal", "bit_type": "count", "count_label": "deferrals", "cooldown": 3, "gear": {"pressure": {"calm": 1.0, "pushing": 1.0}, "engagement": {"hooked": 1.0}}},
  {"id": "BIT-216", "name": "The Questionnaire", "archetypes": ["b2b_saas"], "cooldown": 4, "gear": {"engagement": {"hooked": 2.0, "stunned": 1.0}, "pressure": {"pushing": 2.0, "extracting": 1.0}, "suspicion": {"alive": 1.0, "slipping": 1.0}}, "phase_pref": "probing"},
  {"id": "BIT-217", "name": "The Conrad Bit", "archetypes": "universal", "cooldown": 6, "gear": {"pressure": {"extracting": 1.0}, "engagement": {"bored": -2.0, "hooked": 3.0, "stunned": 2.0}}},
  {"id": "BIT-218", "name": "The Introduction", "archetypes": "universal", "cooldown": 4, "gear": {"pressure": {"calm": 1.0, "pushing": 1.0}, "engagement": {"bored": 1.0, "hooked": 2.0, "stunned": 1.0}}},
  {"id": "BIT-219", "name": "The Terrible Notes", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 2.0, "stunned": 1.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-220", "name": "Offscreen Chaos", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 2.0, "stunned": 1.0}, "pressure": {"calm": 1.0, "pushing": 1.0, "extracting": 1.0}}},
  {"id": "BIT-221", "name": "The Name Slip", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0, "stunned": 2.0}, "suspicion": {"slipping": 1.0}}},
  {"id": "BIT-222", "name": "The Overlap", "archetypes": "universal", "bit_type": "count", "count_label": "overlaps", "cooldown": 3, "gear": {"engagement": {"bored": 2.0, "hooked": 1.0}, "pressure": {"calm": 1.0}}},
  {"id": "BIT-223", "name": "The Hard Stop", "archetypes": "universal", "cooldown": 5, "gear": {"pressure": {"pushing": 2.0, "extracting": 2.0}, "engagement": {"hooked": 2.0, "stunned": 1.0}}, "phase_pref": "probing"},
  {"id": "BIT-224", "name": "The CC Mistake", "archetypes": "universal", "cooldown": 5, "gear": {"suspicion": {"slipping": 1.0}, "engagement": {"hooked": 2.0, "stunned": 2.0}}},
  {"id": "BIT-225", "name": "The Reference Check", "archetypes": "universal", "cooldown": 5, "gear": {"suspicion": {"alive": 1.0, "slipping": 1.0}, "pressure": {"pushing": 1.0, "extracting": 1.0}, "engagement": {"hooked": 2.0}}, "phase_pref": "probing"},
  {"id": "BIT-226", "name": "The Reintroduction", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": 2.0, "hooked": 1.0}, "pressure": {"calm": 1.0}}},
  {"id": "BIT-227", "name": "The Recap", "archetypes": "universal", "cooldown": 4, "gear": {"pressure": {"calm": 1.0, "pushing": 1.0}, "engagement": {"bored": 2.0, "hooked": 1.0}}},
  {"id": "BIT-228", "name": "The Time Check", "archetypes": "universal", "bit_type": "count", "count_label": "time checks", "cooldown": 3, "gear": {"pressure": {"pushing": 1.0, "extracting": 1.0}, "engagement": {"bored": 1.0, "hooked": 1.0}}},
  {"id": "BIT-229", "name": "The Dropped Thread", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-230", "name": "The Deadline Mention", "archetypes": "universal", "cooldown": 4, "gear": {"suspicion": {"slipping": 1.0, "foregone": 2.0}, "pressure": {"extracting": 3.0, "pushing": 2.0}, "engagement": {"bored": 2.0}}, "phase_pref": "probing"},
  {"id": "BIT-231", "name": "The Competing Vendor", "archetypes": "universal", "cooldown": 4, "gear": {"suspicion": {"slipping": 2.0, "foregone": 1.0}, "pressure": {"extracting": 3.0, "pushing": 2.0}, "engagement": {"bored": 2.0, "hooked": 1.0}}, "phase_pref": "probing"},
  {"id": "BIT-232", "name": "The Weather", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 1.0}, "pressure": {"calm": 2.0}}, "phase_pref": "opening"},
  {"id": "BIT-301", "name": "Technical Difficulties", "archetypes": "universal", "cooldown": 3, "gear": {"suspicion": {"slipping": 1.0}, "pressure": {"pushing": 2.0, "extracting": 3.0}}},
  {"id": "BIT-302", "name": "The Dog Bit", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0, "stunned": 0.0}}},
  {"id": "BIT-303", "name": "The Insect Bit", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": 2.0, "hooked": 2.0, "stunned": 1.0}}},
  {"id": "BIT-304", "name": "The Heartbeat Bit", "archetypes": ["crypto_investment"], "cooldown": 5, "gear": {"pressure": {"extracting": 3.0}, "engagement": {"hooked": 2.0}}, "phase_pref": "pitching"},
  {"id": "BIT-305", "name": "The Extensive Typing Bit", "archetypes": "universal", "cooldown": 3, "gear": {"pressure": {"pushing": 1.0, "extracting": 2.0}}},
  {"id": "BIT-306", "name": "Room Presence Bits", "archetypes": "universal", "cooldown": 3, "gear": {"pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-307", "name": "The Spill", "archetypes": "universal", "cooldown": 4, "gear": {"pressure": {"pushing": 1.0, "extracting": 1.0}, "engagement": {"bored": 2.0}}},
  {"id": "BIT-308", "name": "The Snot-Burst / Laughter Reaction", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"stunned": 2.0, "hooked": 1.0, "bored": 0.0}}},
  {"id": "BIT-309", "name": "The Late Arrival", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": 2.0, "hooked": 2.0, "stunned": 1.0}}, "phase_pref": "opening"},
  {"id": "BIT-310", "name": "The Scapegoat", "archetypes": "universal", "cooldown": 3, "gear": {"suspicion": {"slipping": 1.0}, "pressure": {"pushing": 1.0, "extracting": 2.0}, "engagement": {"bored": 1.0}}},
  {"id": "BIT-311", "name": "The Sick Day", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": 2.0, "hooked": 2.0, "stunned": 1.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-312", "name": "Barbara", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 2.0, "stunned": 1.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-313", "name": "The Hangover", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": 2.0, "hooked": 2.0, "stunned": 1.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-314", "name": "The Unmuted Door", "archetypes": "universal", "cooldown": 6, "gear": {"engagement": {"bored": 2.0, "hooked": 2.0, "stunned": 2.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-315", "name": "The Wrong Link", "archetypes": "universal", "cooldown": 4, "gear": {"pressure": {"calm": 1.0, "pushing": 1.0}, "engagement": {"bored": 2.0, "hooked": 1.0}}},
  {"id": "BIT-317", "name": "The Update", "archetypes": "universal", "cooldown": 5, "gear": {"pressure": {"calm": 1.0, "pushing": 1.0}, "engagement": {"bored": 2.0, "hooked": 1.0}}},
  {"id": "BIT-318", "name": "The Mute Confusion", "archetypes": "universal", "bit_type": "count", "count_label": "mute incidents", "cooldown": 3, "gear": {"pressure": {"calm": 1.0}, "engagement": {"bored": 2.0, "hooked": 1.0}}},
  {"id": "BIT-319", "name": "The Phone Call", "archetypes": "universal", "cooldown": 5, "gear": {"pressure": {"calm": 1.0, "pushing": 1.0}, "engagement": {"bored": 2.0, "hooked": 1.0}}},
  {"id": "BIT-320", "name": "The Knock", "archetypes": "universal", "cooldown": 5, "gear": {"pressure": {"calm": 1.0}, "engagement": {"bored": 2.0, "hooked": 1.0}}},
  {"id": "BIT-321", "name": "The Child", "archetypes": "universal", "cooldown": 5, "gear": {"pressure": {"calm": 1.0}, "engagement": {"bored": 2.0, "hooked": 1.0, "stunned": 1.0}}},
  {"id": "BIT-322", "name": "The Alarm", "archetypes": "universal", "cooldown": 5, "gear": {"pressure": {"calm": 1.0, "pushing": 1.0}, "engagement": {"bored": 2.0, "hooked": 1.0, "stunned": 1.0}}},
  {"id": "BIT-323", "name": "The Colleague At The Door", "archetypes": "universal", "cooldown": 4, "gear": {"pressure": {"calm": 1.0}, "engagement": {"bored": 2.0, "hooked": 1.0}}},
  {"id": "BIT-324", "name": "The Window", "archetypes": "universal", "cooldown": 4, "gear": {"suspicion": {"slipping": 1.0, "foregone": 1.0}, "pressure": {"calm": 1.0, "pushing": 1.0}, "engagement": {"bored": 3.0, "stunned": 1.0}}, "phase_pref": "drifting"},
  {"id": "BIT-325", "name": "The Admission", "archetypes": "universal", "cooldown": 5, "gear": {"suspicion": {"slipping": 2.0, "foregone": 1.0}, "pressure": {"extracting": 2.0}, "engagement": {"bored": 3.0, "stunned": 2.0}}, "phase_pref": "drifting"},
  {"id": "BIT-326", "name": "The Commute", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 1.0}, "pressure": {"calm": 1.0}}, "phase_pref": "opening"},
  {"id": "BIT-327", "name": "The History Lesson", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 2.0, "stunned": 1.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-328", "name": "The Hobby", "archetypes": "universal", "cooldown": 3, "gear": {"engagement": {"hooked": 3.0, "stunned": 2.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}},
  {"id": "BIT-329", "name": "The Environment", "archetypes": "universal", "cooldown": 5, "gear": {"engagement": {"bored": 2.0, "hooked": 1.0}, "pressure": {"calm": 2.0, "pushing": 1.0}}},
  {"id": "BIT-401", "name": "The Wrong Window Bit", "archetypes": "universal", "cooldown": 4, "gear": {"pressure": {"pushing": 2.0, "extracting": 2.0}, "suspicion": {"slipping": 1.0}}},
  {"id": "BIT-402", "name": "Chat Injection Bit", "archetypes": "universal", "cooldown": 3, "gear": {"pressure": {"calm": 1.0, "pushing": 2.0}, "engagement": {"hooked": 1.0}}},
  {"id": "BIT-403", "name": "Ai Reacting To Spammer Chat", "archetypes": "universal", "cooldown": 4, "gear": {"suspicion": {"alive": 0.0, "slipping": 2.0, "foregone": 1.0}}},
  {"id": "BIT-404", "name": "The Email Signature Bit", "archetypes": "universal", "cooldown": 3, "gear": {"engagement": {"hooked": 1.0}}},
  {"id": "BIT-405", "name": "The Background Bit", "archetypes": "universal", "cooldown": 3, "gear": {"engagement": {"bored": 2.0, "hooked": 2.0, "stunned": 1.0}}},
  {"id": "BIT-406", "name": "The Camera On", "archetypes": "universal", "cooldown": 5, "gear": {"pressure": {"calm": 1.0}, "engagement": {"bored": 2.0, "hooked": 2.0}}},
  {"id": "BIT-407", "name": "The Frozen Screen", "archetypes": "universal", "cooldown": 5, "gear": {"pressure": {"calm": 1.0, "pushing": 1.0}, "engagement": {"bored": 2.0, "stunned": 1.0}}},
  {"id": "BIT-408", "name": "Camera Off", "archetypes": "universal", "cooldown": 6, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0, "stunned": 2.0}, "pressure": {"calm": 1.0, "pushing": 1.0}}, "phase_pref": "opening"},
  {"id": "BIT-501", "name": "The Office Bit", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 1.0}}},
  {"id": "BIT-502", "name": "Personal Background Bit", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0}}},
  {"id": "BIT-503", "name": "Job Title / Company Bit", "archetypes": "universal", "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 1.0}}},
  {"id": "BIT-504", "name": "The Linkedin Bit", "archetypes": "universal", "cooldown": 4, "gear": {"suspicion": {"slipping": -1.0}, "engagement": {"bored": 1.0, "hooked": 2.0}}},
  {"id": "BIT-505", "name": "The Linkedin Profile Bit", "archetypes": "universal", "cooldown": 3, "gear": {"pressure": {"pushing": 1.0, "extracting": 1.0}}},
  {"id": "BIT-506", "name": "The Oversight Bit", "archetypes": "universal", "cooldown": 4, "gear": {"suspicion": {"slipping": 1.0}, "pressure": {"pushing": 2.0, "extracting": 1.0}}},
  {"id": "BIT-507", "name": "The Fiji Callback", "archetypes": "universal", "fuel_hooks": ["browsed_tmi"], "cooldown": 6, "gear": {"engagement": {"bored": 1.0, "hooked": 3.0, "stunned": 3.0}, "suspicion": {"alive": 1.0, "slipping": 2.0}}},
  {"id": "BIT-508", "name": "Have We Spoken", "archetypes": "universal", "fuel_hooks": ["prior_contact"], "cooldown": 5, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0, "stunned": 2.0}, "suspicion": {"alive": 1.0, "slipping": 2.0}}},
  {"id": "BIT-509", "name": "You Were Going To", "archetypes": "universal", "fuel_hooks": ["call_callback"], "cooldown": 4, "gear": {"pressure": {"pushing": 1.0, "extracting": 2.0}, "engagement": {"bored": 1.0, "hooked": 2.0}}},
  {"id": "BIT-510", "name": "I Thought You Said", "archetypes": "universal", "fuel_hooks": ["call_claim"], "cooldown": 5, "gear": {"pressure": {"extracting": 2.0, "pushing": 1.0}, "suspicion": {"alive": 1.0, "slipping": 1.0}, "engagement": {"hooked": 2.0, "stunned": 1.0}}},
  {"id": "BIT-511", "name": "You Were Going To Send", "archetypes": "universal", "fuel_hooks": ["call_commitment"], "cooldown": 5, "gear": {"pressure": {"pushing": 2.0, "extracting": 2.0}, "engagement": {"bored": 1.0, "hooked": 2.0}, "suspicion": {"slipping": 1.0}}},
  {"id": "BIT-512", "name": "Are You In", "archetypes": "universal", "fuel_hooks": ["office_location"], "cooldown": 4, "gear": {"engagement": {"bored": 1.0, "hooked": 2.0, "stunned": 1.0}, "suspicion": {"alive": 1.0}}},
  {"id": "BIT-513", "name": "I Saw In Your Materials", "archetypes": "universal", "fuel_hooks": ["attachment_facts"], "cooldown": 4, "gear": {"engagement": {"hooked": 3.0, "stunned": 2.0, "bored": -1.0}, "pressure": {"pushing": 1.0, "extracting": 2.0}}},
  {"id": "BIT-514", "name": "The Prep Mismatch", "archetypes": "universal", "cooldown": 5, "gear": {"suspicion": {"alive": 1.0}, "engagement": {"hooked": 2.0, "stunned": 1.0}, "pressure": {"pushing": 1.0}}},
  {"id": "BIT-601", "name": "The Networker", "status": "parked", "park_reason": "no_producer", "archetypes": "universal", "fuel_hooks": ["connection_count"], "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 2.0}}},
  {"id": "BIT-602", "name": "Condolences", "status": "parked", "park_reason": "no_producer", "archetypes": "universal", "fuel_hooks": ["company_news"], "cooldown": 5, "gear": {"pressure": {"calm": 2.0}, "engagement": {"bored": 1.0, "hooked": 3.0}}},
  {"id": "BIT-603", "name": "Tenure Math", "status": "parked", "park_reason": "no_producer", "archetypes": "universal", "fuel_hooks": ["employer_dates"], "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 2.0}}},
  {"id": "BIT-604", "name": "Glassdoor", "status": "parked", "park_reason": "no_producer", "archetypes": "universal", "fuel_hooks": ["company_rating"], "cooldown": 5, "gear": {"pressure": {"pushing": 1.0}, "engagement": {"bored": 1.0, "hooked": 3.0}}},
  {"id": "BIT-605", "name": "The Alumni", "status": "parked", "park_reason": "no_producer", "archetypes": "universal", "fuel_hooks": ["school"], "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 1.0}}},
  {"id": "BIT-606", "name": "The Relocator", "status": "parked", "park_reason": "no_producer", "archetypes": "universal", "fuel_hooks": ["relocation_trail"], "cooldown": 4, "gear": {"engagement": {"bored": 2.0, "hooked": 1.0}}},
  {"id": "BIT-607", "name": "Open To Work", "status": "parked", "park_reason": "no_producer", "archetypes": "universal", "fuel_hooks": ["otw_badge"], "cooldown": 5, "gear": {"suspicion": {"foregone": 1.0}, "engagement": {"hooked": 3.0, "stunned": 1.0}}},
  {"id": "BIT-608", "name": "The Headline", "status": "parked", "park_reason": "no_producer", "archetypes": "universal", "fuel_hooks": ["headline_buzzwords"], "cooldown": 3, "gear": {"engagement": {"bored": 2.0, "hooked": 1.0}}},
  {"id": "BIT-701", "name": "The Callback Hook", "archetypes": "universal", "cooldown": 6, "intensity": 0.4, "gear": {"suspicion": {"alive": 2.0, "slipping": 1.0, "foregone": -1.0}, "pressure": {"extracting": 2.0}, "engagement": {"hooked": 2.0}}},
  {"id": "BIT-702", "name": "The Guilt Pivot", "archetypes": "universal", "cooldown": 6, "intensity": 0.5, "gear": {"engagement": {"bored": 3.0, "hooked": 0.0, "stunned": -1.0}, "pressure": {"extracting": 2.0}}},
  {"id": "BIT-703", "name": "The Confused Recap", "archetypes": "universal", "cooldown": 6, "intensity": 0.6, "gear": {"pressure": {"extracting": 3.0}, "engagement": {"hooked": 1.0}}},
  {"id": "BIT-704", "name": "The Colleague Pull", "archetypes": "universal", "cooldown": 6, "intensity": 0.5, "gear": {"engagement": {"hooked": 2.0, "stunned": 2.0}}},
  {"id": "BIT-705", "name": "The Send-Off", "archetypes": "universal", "cooldown": 6, "intensity": 0.3, "gear": {"suspicion": {"alive": 3.0, "slipping": 0.0, "foregone": -2.0}, "engagement": {"hooked": 2.0}}},
];
