// SpamViking — Bits Registry
// Source of truth: SpamViking_BitsRegistry.json + session edits
// Last updated: August 16, 2026
// CRITICAL: archetypes field restored — do not remove until PE updates scorer gate

export const BITS = [
  {
    "id": "BIT-101",
    "name": "The Echo",
    "status": "active",
    "bit_type": "count",
    "count_label": "echoes",
    "fuel_hooks": [],
    "cooldown": 3,
    "rungs": 4,
    "rung_spacing": {
      "min_between": 2,
      "rung_3_earliest_turn": 6
    },
    "family": "verbal",
    "absurdity": 3,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-102",
    "name": "Old Saws",
    "status": "active",
    "cooldown": 4,
    "rungs": 3,
    "rung_spacing": {
      "min_between": 3
    },
    "pool": "middle",
    "family": "verbal",
    "absurdity": 3,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-103",
    "name": "The Quotes Bit",
    "status": "active",
    "channel": "video",
    "cooldown": 4,
    "pool": "middle",
    "family": "video",
    "absurdity": 4,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-104",
    "name": "Malaprops",
    "status": "active",
    "bit_type": "count",
    "count_label": "substitutions",
    "cooldown": 2,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 4,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-105",
    "name": "The Eggcorn Bit",
    "status": "active",
    "bit_type": "count",
    "count_label": "eggcorns",
    "cooldown": 3,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 3,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-106",
    "name": "The Metric Bit",
    "status": "parked",
    "cooldown": 4,
    "pool": "early",
    "family": "verbal",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-107",
    "name": "Metric Vs. Imperial",
    "status": "active",
    "cooldown": 4,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 3,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-108",
    "name": "The Acronym Bit",
    "status": "active",
    "cooldown": 3,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 4,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-109",
    "name": "The Buzzword Lag",
    "status": "parked",
    "cooldown": 3,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-110",
    "name": "The Name Trilogy",
    "status": "parked",
    "cooldown": 4,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 2,
    "vocal_tag": "surprised",
    "park_reason": "Andrew review Aug 16 \u2014 name trilogy too complex, parts absorbed elsewhere",
    "archetypes": "universal"
  },
  {
    "id": "BIT-111",
    "name": "The Callback Bit",
    "status": "parked",
    "cooldown": 4,
    "pool": "late",
    "family": "verbal",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-112",
    "name": "The Pause Bit",
    "status": "parked",
    "cooldown": 3,
    "phase_pref": "drifting",
    "trigger": "extended_stall",
    "family": "verbal",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-112b",
    "name": "Still Going?",
    "status": "active",
    "bit_type": "count",
    "count_label": "overheld pauses",
    "cooldown": 3,
    "phase_pref": "drifting",
    "trigger": "extended_stall",
    "family": "verbal",
    "absurdity": 2,
    "max_fires_per_call": 3,
    "vocal_tag": "surprised",
    "archetypes": "universal"
  },
  {
    "id": "BIT-113",
    "name": "The Movie Bit",
    "status": "active",
    "cooldown": 5,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 3,
    "vocal_tag": "excited",
    "requires_context": "spammer has described a product, service, or situation that maps to a film",
    "trigger": "caller_presenting",
    "archetypes": "universal"
  },
  {
    "id": "BIT-114",
    "name": "The Movie Quote / Misquote Bit",
    "status": "active",
    "cooldown": 5,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 3,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-115",
    "name": "The Robot Voice Bit",
    "status": "parked",
    "cooldown": 5,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-116",
    "name": "The Name Collision Bit",
    "status": "parked",
    "cooldown": 3,
    "trigger": "caller_named_competitor",
    "family": "verbal",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-117",
    "name": "The Lyric Bit",
    "status": "active",
    "cooldown": 4,
    "rungs": 4,
    "ceiling": "soft_dead_end",
    "rung_spacing": {
      "min_between": 2,
      "rung_3_earliest_turn": 8,
      "rung_4_earliest_turn": 14
    },
    "pool": "middle",
    "family": "verbal",
    "absurdity": 4,
    "vocal_tag": "excited",
    "requires_context": "spammer has said something that contains a word or phrase matchable to a song lyric",
    "archetypes": "universal"
  },
  {
    "id": "BIT-118",
    "name": "The Negation Drop",
    "status": "active",
    "fuel_hooks": [
      "dossier_negation"
    ],
    "cooldown": 6,
    "phase_pref": "pitching",
    "trigger": "caller_made_claim",
    "family": "verbal",
    "absurdity": 3,
    "vocal_tag": "surprised",
    "requires_context": "spammer has made a specific factual claim about their product or service",
    "archetypes": "universal"
  },
  {
    "id": "BIT-119",
    "name": "The Hype Spiral",
    "status": "active",
    "cooldown": 5,
    "phase_pref": "pitching",
    "trigger": "caller_presenting",
    "pool": "middle",
    "family": "verbal",
    "absurdity": 4,
    "vocal_tag": "excited",
    "requires_context": "spammer has actively pitched their product or service",
    "archetypes": "universal"
  },
  {
    "id": "BIT-120",
    "name": "The Emotional Crescendo",
    "status": "active",
    "cooldown": 5,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 4,
    "vocal_tag": "sad",
    "requires_context": "spammer has said something with emotional or personal resonance",
    "archetypes": "universal"
  },
  {
    "id": "BIT-121",
    "name": "My Name, Actually",
    "status": "parked",
    "cooldown": 4,
    "pool": "early",
    "family": "verbal",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-122",
    "name": "I Get That A Lot",
    "status": "parked",
    "cooldown": 6,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 1,
    "park_reason": "Andrew review Aug 5 \u2014 too thin",
    "archetypes": "universal"
  },
  {
    "id": "BIT-123",
    "name": "The Strong Opinion",
    "status": "parked",
    "cooldown": 4,
    "pool": "early",
    "family": "verbal",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-124",
    "name": "The Previous Vendor",
    "status": "parked",
    "cooldown": 5,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 3,
    "vocal_tag": "mysterious",
    "park_reason": "Andrew review Aug 16 \u2014 previous vendor beat moved to host prompt texture",
    "archetypes": "universal"
  },
  {
    "id": "BIT-125",
    "name": "The Tangent",
    "status": "parked",
    "bit_type": "count",
    "count_label": "tangents",
    "cooldown": 3,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-126",
    "name": "The Aside",
    "status": "active",
    "cooldown": 4,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 4,
    "vocal_tag": "neutral",
    "archetypes": "universal"
  },
  {
    "id": "BIT-127",
    "name": "The Correction",
    "status": "parked",
    "bit_type": "count",
    "count_label": "self-corrections",
    "cooldown": 3,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 1,
    "park_reason": "Andrew review Aug 5 \u2014 too thin",
    "archetypes": "universal"
  },
  {
    "id": "BIT-128",
    "name": "The Pivot Question",
    "status": "parked",
    "cooldown": 3,
    "phase_pref": "drifting",
    "trigger": "extended_stall",
    "pool": "middle",
    "family": "verbal",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-129",
    "name": "The Reframe",
    "status": "parked",
    "cooldown": 3,
    "phase_pref": "drifting",
    "trigger": "extended_stall",
    "pool": "middle",
    "family": "verbal",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-130",
    "name": "How Are You",
    "status": "parked",
    "bit_type": "count",
    "count_label": "genuine answers",
    "cooldown": 5,
    "trigger": "phase:opening",
    "family": "structural",
    "absurdity": 2,
    "park_reason": "Andrew review Aug 5 \u2014 too thin",
    "archetypes": "universal"
  },
  {
    "id": "BIT-131",
    "name": "The Busy Escalation",
    "status": "active",
    "bit_type": "count",
    "count_label": "busy exchanges",
    "cooldown": 4,
    "trigger": "phase:opening",
    "family": "structural",
    "absurdity": 4,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-132",
    "name": "The Expansion News",
    "status": "parked",
    "cooldown": 6,
    "max_fires_per_call": 1,
    "family": "structural",
    "absurdity": 3,
    "pool": "middle",
    "vocal_tag": "excited",
    "park_reason": "Andrew review Aug 16 \u2014 expansion news too thin without prior contact context",
    "archetypes": "universal"
  },
  {
    "id": "BIT-133",
    "name": "Audio Verification",
    "status": "active",
    "bit_type": "count",
    "count_label": "audio checks",
    "cooldown": 3,
    "trigger": "phase:opening",
    "family": "structural",
    "absurdity": 4,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-134",
    "name": "Six Degrees",
    "status": "active",
    "cooldown": 5,
    "family": "structural",
    "absurdity": 2,
    "pool": "middle",
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-136",
    "name": "The Commute",
    "status": "parked",
    "park_reason": "superseded by BIT-326",
    "cooldown": 4,
    "family": "personal",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-137",
    "name": "The History Lesson",
    "status": "parked",
    "park_reason": "superseded by BIT-327",
    "cooldown": 4,
    "family": "personal",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-138",
    "name": "The Hobby",
    "status": "parked",
    "park_reason": "superseded by BIT-328",
    "cooldown": 3,
    "rungs": 4,
    "ceiling": "soft_dead_end",
    "rung_spacing": {
      "min_between": 2,
      "rung_3_earliest_turn": 8,
      "rung_4_earliest_turn": 14
    },
    "family": "personal",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-139",
    "name": "Genealogy",
    "status": "active",
    "cooldown": 5,
    "pool": "middle",
    "family": "personal",
    "absurdity": 3,
    "vocal_tag": "content",
    "archetypes": "universal"
  },
  {
    "id": "BIT-140",
    "name": "The Bucket List",
    "status": "active",
    "cooldown": 5,
    "pool": "middle",
    "family": "personal",
    "absurdity": 3,
    "vocal_tag": "sad",
    "archetypes": "universal"
  },
  {
    "id": "BIT-141",
    "name": "Sports Expectations",
    "status": "active",
    "cooldown": 5,
    "pool": "middle",
    "family": "personal",
    "absurdity": 3,
    "vocal_tag": "sad",
    "archetypes": "universal"
  },
  {
    "id": "BIT-142",
    "name": "Fantasy Football",
    "status": "active",
    "cooldown": 5,
    "pool": "middle",
    "family": "personal",
    "absurdity": 3,
    "vocal_tag": "sad",
    "archetypes": "universal"
  },
  {
    "id": "BIT-143",
    "name": "The Challenge Riff",
    "status": "parked",
    "cooldown": 5,
    "pool": "middle",
    "family": "personal",
    "absurdity": 2,
    "park_reason": "Andrew review Aug 5 \u2014 too thin",
    "archetypes": "universal"
  },
  {
    "id": "BIT-144",
    "name": "Celebrity Sighting",
    "status": "active",
    "cooldown": 5,
    "pool": "middle",
    "family": "personal",
    "absurdity": 3,
    "vocal_tag": "content",
    "archetypes": "universal"
  },
  {
    "id": "BIT-145",
    "name": "The Sniglet",
    "status": "active",
    "cooldown": 4,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 4,
    "max_fires_per_call": 3,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-146",
    "name": "The Innuendo",
    "status": "active",
    "cooldown": 4,
    "rungs": 4,
    "ceiling": "soft_dead_end",
    "rung_spacing": {
      "min_between": 2,
      "rung_3_earliest_turn": 8,
      "rung_4_earliest_turn": 14
    },
    "pool": "middle",
    "family": "personal",
    "absurdity": 4,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-147",
    "name": "The Relationship",
    "status": "active",
    "cooldown": 5,
    "rungs": 4,
    "ceiling": "soft_dead_end",
    "rung_spacing": {
      "min_between": 2,
      "rung_3_earliest_turn": 10,
      "rung_4_earliest_turn": 16
    },
    "pool": "middle",
    "family": "personal",
    "absurdity": 3,
    "vocal_tag": "sad",
    "archetypes": "universal"
  },
  {
    "id": "BIT-148",
    "name": "The Name Thing",
    "status": "active",
    "bit_type": "count",
    "count_label": "name_uses",
    "cooldown": 3,
    "rungs": 5,
    "ceiling": "soft_dead_end",
    "rung_spacing": {
      "min_between": 1,
      "rung_4_earliest_turn": 6
    },
    "pool": "middle",
    "family": "verbal",
    "absurdity": 3,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-149",
    "name": "The Vernacular",
    "status": "active",
    "bit_type": "count",
    "count_label": "vernacular_uses",
    "cooldown": 4,
    "pool": "middle",
    "family": "verbal",
    "absurdity": 4,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-201",
    "name": "The Competitor Bit",
    "cooldown": 4,
    "pool": "middle",
    "status": "parked",
    "family": "structural",
    "absurdity": 2,
    "vocal_tag": "excited",
    "park_reason": "Andrew review Aug 16 \u2014 competitor reference too thin",
    "requires_context": "spammer has mentioned their company or pitched their offering",
    "archetypes": "universal"
  },
  {
    "cooldown": 5,
    "id": "BIT-202",
    "name": "The Foreshadowing Bit",
    "lane": "stall",
    "stall_type": "hunt",
    "trigger": "commitment_push",
    "status": "parked",
    "family": "structural",
    "absurdity": 1,
    "park_reason": "Andrew review Aug 5 \u2014 too thin, forward reference without payoff",
    "archetypes": "universal"
  },
  {
    "id": "BIT-203",
    "name": "The Agenda Bit",
    "status": "active",
    "cooldown": 3,
    "family": "structural",
    "absurdity": 2,
    "vocal_tag": "excited",
    "requires_context": "spammer has been pitching for at least 2 turns",
    "trigger": "caller_presenting",
    "archetypes": "universal"
  },
  {
    "cooldown": 4,
    "id": "BIT-204",
    "name": "The Nda Bit",
    "lane": "stall",
    "stall_type": "hunt",
    "trigger": "documentation_mentioned",
    "status": "active",
    "family": "structural",
    "absurdity": 2,
    "vocal_tag": "mysterious",
    "archetypes": "universal"
  },
  {
    "id": "BIT-205",
    "name": "The Reschedule Bit",
    "status": "parked",
    "cooldown": 4,
    "family": "structural",
    "absurdity": 3,
    "vocal_tag": "excited",
    "park_reason": "Andrew review Aug 16 \u2014 reschedule bit too procedural, absorbed into stall family",
    "archetypes": "universal"
  },
  {
    "id": "BIT-206",
    "name": "The Document Request + Photo Bit",
    "status": "active",
    "cooldown": 4,
    "family": "structural",
    "absurdity": 2,
    "vocal_tag": "excited",
    "trigger": "caller_presenting",
    "requires_context": "spammer has mentioned materials, a deck, or documentation",
    "archetypes": "universal"
  },
  {
    "id": "BIT-207",
    "name": "The Tom Echo",
    "status": "active",
    "bit_type": "count",
    "count_label": "check-ins",
    "cooldown": 3,
    "pool": "middle",
    "family": "structural",
    "absurdity": 2,
    "rungs": 3,
    "rung_spacing": {
      "min_between": 2
    },
    "vocal_tag": "excited",
    "trigger": "caller_presenting",
    "requires_context": "spammer has begun a formal pitch or evaluation conversation",
    "archetypes": "universal"
  },
  {
    "id": "BIT-208",
    "name": "The Forwarded Email Bit",
    "status": "parked",
    "cooldown": 4,
    "pool": "middle",
    "family": "structural",
    "absurdity": 1,
    "park_reason": "Andrew review Aug 5 \u2014 too thin",
    "archetypes": "universal"
  },
  {
    "id": "BIT-209",
    "name": "The Previous Call Bit",
    "status": "parked",
    "cooldown": 6,
    "pool": "early",
    "family": "structural",
    "absurdity": 1,
    "park_reason": "Andrew review Aug 5 \u2014 too thin",
    "archetypes": "universal"
  },
  {
    "cooldown": 3,
    "id": "BIT-210",
    "name": "Cry Poverty",
    "lane": "stall",
    "stall_type": "hunt",
    "trigger": "commitment_push|pricing_raised",
    "status": "active",
    "family": "stall",
    "absurdity": 2,
    "vocal_tag": "calm",
    "requires_context": "spammer has raised pricing or asked for a commitment",
    "archetypes": "universal"
  },
  {
    "id": "BIT-211",
    "name": "The Silence / The Pile-Up",
    "status": "active",
    "bit_type": "count",
    "count_label": "silences",
    "cooldown": 3,
    "pool": "middle",
    "family": "stall",
    "absurdity": 2,
    "vocal_tag": "calm",
    "archetypes": "universal"
  },
  {
    "cooldown": 4,
    "id": "BIT-212",
    "name": "The Join",
    "pool": "middle",
    "status": "parked",
    "family": "structural",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "cooldown": 5,
    "id": "BIT-213",
    "name": "The Accidental Joiner",
    "pool": "middle",
    "status": "parked",
    "family": "structural",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "cooldown": 5,
    "id": "BIT-214",
    "name": "The Two Spammers",
    "pool": "middle",
    "status": "parked",
    "family": "structural",
    "absurdity": 1,
    "vocal_tag": "surprised",
    "park_reason": "Andrew review Aug 16 \u2014 two spammers situation too rare",
    "archetypes": "universal"
  },
  {
    "cooldown": 3,
    "id": "BIT-215",
    "name": "No You Go",
    "bit_type": "count",
    "count_label": "deferrals",
    "lane": "stall",
    "stall_type": "hold",
    "trigger": "caller_went_quiet",
    "status": "parked",
    "family": "stall",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "cooldown": 4,
    "id": "BIT-216",
    "name": "The Questionnaire",
    "phase_pref": "probing",
    "trigger": "caller_presenting",
    "status": "active",
    "family": "structural",
    "absurdity": 2,
    "vocal_tag": "excited",
    "requires_context": "spammer has been pitching for at least 3 turns \u2014 probing phase underway",
    "archetypes": "universal"
  },
  {
    "cooldown": 6,
    "id": "BIT-217",
    "name": "The Conrad Bit",
    "pool": "middle",
    "status": "parked",
    "rungs": 4,
    "ceiling": "soft_dead_end",
    "rung_spacing": {
      "min_between": 2,
      "rung_3_earliest_turn": 8,
      "rung_4_earliest_turn": 14
    },
    "family": "structural",
    "absurdity": 1,
    "vocal_tag": "mysterious",
    "park_reason": "Andrew review Aug 16 \u2014 Bench system work not a bit",
    "archetypes": "universal"
  },
  {
    "cooldown": 4,
    "id": "BIT-218",
    "name": "The Introduction",
    "pool": "early",
    "status": "parked",
    "family": "stall",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-219",
    "name": "The Terrible Notes",
    "cooldown": 4,
    "pool": "middle",
    "status": "parked",
    "family": "structural",
    "absurdity": 1,
    "vocal_tag": "excited",
    "park_reason": "Andrew review Aug 16 \u2014 terrible notes too thin",
    "archetypes": "universal"
  },
  {
    "id": "BIT-220",
    "name": "Offscreen Chaos",
    "cooldown": 4,
    "lane": "gag",
    "status": "active",
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-221",
    "name": "The Name Slip",
    "cooldown": 5,
    "pool": "early",
    "status": "active",
    "family": "structural",
    "absurdity": 2,
    "vocal_tag": "surprised",
    "archetypes": "universal"
  },
  {
    "id": "BIT-222",
    "name": "The Overlap",
    "bit_type": "count",
    "count_label": "overlaps",
    "cooldown": 3,
    "pool": "middle",
    "status": "parked",
    "family": "stall",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-223",
    "name": "The Clock",
    "cooldown": 3,
    "phase_pref": "probing",
    "lane": "stall",
    "stall_type": "hunt",
    "trigger": "commitment_push",
    "status": "active",
    "rungs": 3,
    "ceiling": "soft_dead_end",
    "rung_spacing": {
      "min_between": 3,
      "rung_3_earliest_turn": 10
    },
    "pool": "middle",
    "family": "stall",
    "absurdity": 2,
    "vocal_tag": "calm",
    "requires_context": "spammer has been pushing for a decision for at least 2 turns",
    "archetypes": "universal"
  },
  {
    "id": "BIT-224",
    "name": "The CC Mistake",
    "cooldown": 5,
    "pool": "early",
    "status": "parked",
    "family": "structural",
    "absurdity": 1,
    "vocal_tag": "excited",
    "park_reason": "Andrew review Aug 16 \u2014 CC mistake needs to come earlier, parked pending retrigger",
    "archetypes": "universal"
  },
  {
    "id": "BIT-225",
    "name": "The Reference Check",
    "cooldown": 5,
    "phase_pref": "probing",
    "trigger": "documentation_mentioned",
    "status": "active",
    "family": "structural",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-226",
    "name": "The Reintroduction",
    "cooldown": 5,
    "pool": "middle",
    "status": "parked",
    "family": "structural",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-227",
    "name": "The Recap",
    "cooldown": 4,
    "pool": "late",
    "status": "active",
    "family": "structural",
    "absurdity": 2,
    "vocal_tag": "excited",
    "trigger": "documentation_mentioned",
    "archetypes": "universal"
  },
  {
    "id": "BIT-228",
    "name": "The Time Check",
    "bit_type": "count",
    "count_label": "time checks",
    "cooldown": 3,
    "pool": "middle",
    "status": "parked",
    "family": "stall",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-229",
    "name": "The Dropped Thread",
    "cooldown": 4,
    "pool": "middle",
    "status": "active",
    "family": "structural",
    "absurdity": 2,
    "vocal_tag": "calm",
    "requires_context": "spammer has said at least 3 substantive things \u2014 something to return to",
    "trigger": "caller_presenting",
    "archetypes": "universal"
  },
  {
    "id": "BIT-230",
    "name": "The Deadline Mention",
    "cooldown": 4,
    "phase_pref": "probing",
    "trigger": "phase:probing",
    "pool": "late",
    "status": "parked",
    "family": "stall",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-231",
    "name": "The Competing Vendor",
    "cooldown": 4,
    "phase_pref": "probing",
    "trigger": "phase:probing",
    "status": "parked",
    "family": "structural",
    "absurdity": 1,
    "vocal_tag": "excited",
    "park_reason": "Andrew review Aug 16 \u2014 competing vendor too thin outside probing phase",
    "archetypes": "universal"
  },
  {
    "id": "BIT-232",
    "name": "The Weather",
    "cooldown": 4,
    "trigger": "phase:opening",
    "status": "parked",
    "family": "structural",
    "absurdity": 1,
    "vocal_tag": "excited",
    "park_reason": "Superseded by BIT-902 (The Weather Remark) in 900s opener block",
    "archetypes": "universal"
  },
  {
    "id": "BIT-233",
    "name": "The Approver Hunt",
    "lane": "stall",
    "cooldown": 1,
    "ceiling": "soft_dead_end",
    "stall_type": "hunt",
    "rungs": 5,
    "trigger": "documentation_mentioned",
    "status": "active",
    "max_fires_per_call": 5,
    "family": "stall",
    "absurdity": 2,
    "vocal_tag": "excited",
    "requires_context": "spammer has been pushing for commitment \u2014 approval hunt is warranted",
    "archetypes": "universal"
  },
  {
    "id": "BIT-234",
    "name": "The Tip Of The Tongue",
    "status": "active",
    "bit_type": "count",
    "count_label": "question attempts",
    "family": "structural",
    "pool": "middle",
    "cooldown": 3,
    "rungs": 4,
    "ceiling": "hard",
    "rung_spacing": {
      "min_between": 3
    },
    "absurdity": 4,
    "vocal_tag": "excited",
    "trigger": "documentation_mentioned",
    "archetypes": "universal"
  },
  {
    "id": "BIT-238",
    "name": "The Deflection",
    "status": "active",
    "family": "structural",
    "pool": "middle",
    "cooldown": 2,
    "rungs": 4,
    "ceiling": "soft_dead_end",
    "rung_spacing": {
      "min_between": 1
    },
    "absurdity": 4,
    "vocal_tag": "mysterious",
    "trigger": "commitment_push",
    "requires_context": "spammer has asked for personal information",
    "archetypes": "universal"
  },
  {
    "id": "BIT-239",
    "name": "The Camera Reason",
    "status": "active",
    "family": "structural",
    "pool": "early",
    "trigger": "none",
    "cooldown": 999,
    "max_fires_per_call": 1,
    "rungs": 3,
    "rung_spacing": {
      "min_between": 2
    },
    "absurdity": 4,
    "vocal_tag": "content",
    "channel": "video",
    "archetypes": "universal"
  },
  {
    "cooldown": 3,
    "id": "BIT-301",
    "name": "Technical Difficulties",
    "pool": "middle",
    "status": "active",
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-302",
    "name": "The Dog Bit",
    "status": "active",
    "cooldown": 4,
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-303",
    "name": "The Insect Bit",
    "status": "active",
    "cooldown": 5,
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "cooldown": 5,
    "id": "BIT-304",
    "name": "The Ring / Whoop",
    "phase_pref": "pitching",
    "trigger": "commitment_push",
    "status": "active",
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "requires_context": "spammer has asked for a credit card, payment, or high-stakes commitment",
    "archetypes": "universal"
  },
  {
    "id": "BIT-305",
    "name": "The Extensive Typing Bit",
    "status": "active",
    "cooldown": 3,
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-306",
    "name": "Room Presence Bits",
    "status": "active",
    "cooldown": 3,
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "cooldown": 4,
    "id": "BIT-307",
    "name": "The Spill",
    "lane": "gag",
    "status": "active",
    "max_fires_per_call": 1,
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "neutral",
    "archetypes": "universal"
  },
  {
    "id": "BIT-308",
    "name": "The Snot-Burst / Laughter Reaction",
    "status": "parked",
    "cooldown": 5,
    "family": "environment",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-309",
    "name": "The Late Arrival",
    "status": "active",
    "cooldown": 5,
    "trigger": "call_turn_1",
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "surprised",
    "archetypes": "universal"
  },
  {
    "cooldown": 3,
    "id": "BIT-310",
    "name": "The Scapegoat",
    "status": "active",
    "family": "personal",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-311",
    "name": "The Sick Day",
    "cooldown": 5,
    "status": "active",
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-312",
    "name": "Barbara",
    "cooldown": 4,
    "pool": "middle",
    "status": "active",
    "family": "personal",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-313",
    "name": "The Hangover",
    "cooldown": 5,
    "lane": "gag",
    "status": "active",
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-314",
    "name": "The Unmuted Door",
    "cooldown": 6,
    "lane": "gag",
    "status": "active",
    "max_fires_per_call": 1,
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "surprised",
    "archetypes": "universal"
  },
  {
    "id": "BIT-315",
    "name": "The Wrong Link",
    "cooldown": 4,
    "pool": "middle",
    "status": "active",
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-317",
    "name": "The Update",
    "cooldown": 5,
    "pool": "middle",
    "status": "active",
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-318",
    "name": "The Mute Confusion",
    "bit_type": "count",
    "count_label": "mute incidents",
    "cooldown": 3,
    "pool": "middle",
    "status": "active",
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-319",
    "name": "The Phone Call",
    "cooldown": 5,
    "pool": "middle",
    "status": "active",
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-320",
    "name": "The Knock",
    "cooldown": 5,
    "lane": "gag",
    "status": "active",
    "max_fires_per_call": 1,
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-321",
    "name": "The Child",
    "cooldown": 5,
    "pool": "middle",
    "status": "active",
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-322",
    "name": "The Alarm",
    "cooldown": 5,
    "pool": "middle",
    "status": "active",
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-323",
    "name": "The Colleague At The Door",
    "cooldown": 4,
    "pool": "middle",
    "status": "active",
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-324",
    "name": "The Window",
    "cooldown": 4,
    "phase_pref": "drifting",
    "trigger": "extended_stall",
    "status": "active",
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "calm",
    "archetypes": "universal"
  },
  {
    "id": "BIT-325",
    "name": "The Admission",
    "cooldown": 5,
    "phase_pref": "drifting",
    "trigger": "extended_stall",
    "status": "active",
    "family": "personal",
    "absurdity": 2,
    "vocal_tag": "calm",
    "archetypes": "universal"
  },
  {
    "id": "BIT-326",
    "name": "The Commute",
    "cooldown": 4,
    "status": "active",
    "family": "environment",
    "absurdity": 2,
    "pool": "middle",
    "vocal_tag": "content",
    "archetypes": "universal"
  },
  {
    "id": "BIT-327",
    "name": "The History Lesson",
    "cooldown": 4,
    "pool": "middle",
    "status": "parked",
    "family": "personal",
    "absurdity": 1,
    "vocal_tag": "content",
    "park_reason": "Andrew review Aug 16 \u2014 directive not yet authored",
    "archetypes": "universal"
  },
  {
    "id": "BIT-328",
    "name": "The Hobby",
    "cooldown": 3,
    "trigger": "caller_named_hobby",
    "pool": "middle",
    "status": "active",
    "family": "personal",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-329",
    "name": "The Environment",
    "cooldown": 5,
    "lane": "gag",
    "status": "parked",
    "max_fires_per_call": 2,
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "neutral",
    "park_reason": "Split into BIT-330 (Dishwasher), BIT-331 (Thunderstorm), BIT-332 (Dump Truck), BIT-333 (Plane Overhead)",
    "archetypes": "universal"
  },
  {
    "id": "BIT-401",
    "name": "The Wrong Window Bit",
    "cooldown": 4,
    "pool": "middle",
    "status": "active",
    "family": "video",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "cooldown": 3,
    "id": "BIT-402",
    "name": "Chat Injection Bit",
    "pool": "middle",
    "status": "active",
    "channel": "video",
    "family": "video",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-403",
    "name": "Ai Reacting To Spammer Chat",
    "status": "active",
    "cooldown": 4,
    "pool": "middle",
    "channel": "video",
    "trigger": "caller_questioned_humanity",
    "family": "video",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-404",
    "name": "The Email Signature Bit",
    "status": "active",
    "cooldown": 3,
    "pool": "middle",
    "family": "video",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-405",
    "name": "The Background Bit",
    "status": "active",
    "cooldown": 3,
    "pool": "middle",
    "channel": "video",
    "family": "video",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "cooldown": 5,
    "id": "BIT-406",
    "name": "The Camera On",
    "status": "active",
    "pool": "middle",
    "channel": "video",
    "family": "video",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-407",
    "name": "The Frozen Screen",
    "cooldown": 5,
    "lane": "gag",
    "status": "active",
    "channel": "video",
    "family": "video",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-408",
    "name": "Camera Off",
    "cooldown": 6,
    "phase_pref": "opening",
    "lane": "gag",
    "trigger": "call_turn_1",
    "status": "parked",
    "channel": "video",
    "family": "video",
    "absurdity": 1,
    "vocal_tag": "excited",
    "park_reason": "Replaced by BIT-239 (Camera Reason) \u2014 flat one-beat with no arc, TMI pool now in host prompt",
    "archetypes": "universal"
  },
  {
    "id": "BIT-501",
    "name": "The Office Bit",
    "status": "active",
    "cooldown": 4,
    "pool": "middle",
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-502",
    "name": "Personal Background Bit",
    "status": "parked",
    "cooldown": 4,
    "park_reason": "target_background hook unconfirmed \u2014 no Scouting producer yet",
    "family": "dossier",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-503",
    "name": "Job Title / Company Bit",
    "status": "active",
    "cooldown": 4,
    "pool": "middle",
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "excited",
    "requires_context": "spammer has mentioned their company or title",
    "trigger": "caller_presenting",
    "archetypes": "universal"
  },
  {
    "cooldown": 4,
    "id": "BIT-504",
    "name": "The Linkedin Bit",
    "pool": "late",
    "status": "active",
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-505",
    "name": "The Linkedin Profile Bit",
    "status": "parked",
    "cooldown": 3,
    "park_reason": "sender_linkedin hook confirmed dead \u2014 no producer",
    "family": "dossier",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "cooldown": 4,
    "id": "BIT-506",
    "name": "The Oversight Bit",
    "pool": "late",
    "status": "active",
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-507",
    "name": "The Fiji Callback",
    "fuel_hooks": [
      "browsed_tmi"
    ],
    "cooldown": 6,
    "trigger": "browsed_tmi",
    "status": "active",
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "mysterious",
    "requires_context": "browsed_tmi hook confirmed \u2014 Fiji or travel data available",
    "archetypes": "universal"
  },
  {
    "id": "BIT-508",
    "name": "Have We Spoken",
    "fuel_hooks": [
      "has_prior_contact"
    ],
    "cooldown": 5,
    "trigger": "has_prior_contact",
    "status": "active",
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "excited",
    "requires_context": "prior contact confirmed in dossier",
    "archetypes": "universal"
  },
  {
    "id": "BIT-509",
    "name": "You Were Going To",
    "fuel_hooks": [
      "prior_call_count"
    ],
    "cooldown": 4,
    "trigger": "has_prior_contact",
    "status": "active",
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "excited",
    "requires_context": "prior contact confirmed, spammer made a commitment",
    "archetypes": "universal"
  },
  {
    "id": "BIT-510",
    "name": "I Thought You Said",
    "fuel_hooks": [
      "prior_call_count"
    ],
    "cooldown": 5,
    "trigger": "has_prior_contact",
    "status": "active",
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "excited",
    "requires_context": "prior contact confirmed, spammer made a claim",
    "archetypes": "universal"
  },
  {
    "id": "BIT-511",
    "name": "You Were Going To Send",
    "fuel_hooks": [
      "prior_call_count"
    ],
    "cooldown": 5,
    "trigger": "has_prior_contact",
    "status": "active",
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "excited",
    "requires_context": "prior contact confirmed, spammer committed to send materials",
    "archetypes": "universal"
  },
  {
    "id": "BIT-512",
    "name": "Are You In",
    "fuel_hooks": [
      "prior_call_count"
    ],
    "cooldown": 4,
    "trigger": "has_prior_contact",
    "status": "active",
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "excited",
    "requires_context": "prior contact confirmed, location known",
    "archetypes": "universal"
  },
  {
    "id": "BIT-513",
    "name": "I Saw In Your Materials",
    "fuel_hooks": [
      "prior_call_count"
    ],
    "cooldown": 4,
    "trigger": "has_prior_contact",
    "status": "active",
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "excited",
    "requires_context": "prior contact confirmed, materials received",
    "archetypes": "universal"
  },
  {
    "id": "BIT-514",
    "name": "The Prep Mismatch",
    "cooldown": 5,
    "pool": "late",
    "status": "active",
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-515",
    "name": "The Movie Arc",
    "cooldown": 4,
    "rungs": 4,
    "ceiling": "soft_dead_end",
    "rung_spacing": {
      "min_between": 2,
      "rung_3_earliest_turn": 10,
      "rung_4_earliest_turn": 16
    },
    "pool": "middle",
    "status": "active",
    "max_fires_per_call": 4,
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "excited",
    "requires_context": "spammer has described a narrative arc in their pitch",
    "trigger": "caller_presenting",
    "archetypes": "universal"
  },
  {
    "id": "BIT-516",
    "name": "The Credential",
    "cooldown": 5,
    "rungs": 4,
    "ceiling": "soft_dead_end",
    "rung_spacing": {
      "min_between": 2,
      "rung_3_earliest_turn": 10,
      "rung_4_earliest_turn": 16
    },
    "pool": "middle",
    "status": "active",
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "excited",
    "requires_context": "spammer has mentioned a credential, certification, or qualification",
    "trigger": "caller_presenting",
    "archetypes": "universal"
  },
  {
    "id": "BIT-517",
    "name": "The Email Callback",
    "status": "active",
    "fuel_hooks": [
      "email_dossier"
    ],
    "cooldown": 4,
    "pool": "middle",
    "bit_type": "count",
    "count_label": "callbacks",
    "family": "dossier",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-601",
    "name": "The Networker",
    "status": "parked",
    "park_reason": "no_producer",
    "fuel_hooks": [],
    "cooldown": 4,
    "family": "dossier",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "fuel_hooks": [
      "company_news"
    ],
    "cooldown": 5,
    "id": "BIT-602",
    "name": "Condolences",
    "park_reason": "no_producer",
    "park_note": "fuel hook has no live Scouting producer. Person/LinkedIn enrichment not yet built. Re-activate only when a producer writes this hook to targets. Option A \u2014 June 2026.",
    "status": "parked",
    "family": "dossier",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-603",
    "name": "Tenure Math",
    "status": "parked",
    "park_reason": "no_producer",
    "fuel_hooks": [],
    "cooldown": 4,
    "family": "dossier",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "fuel_hooks": [],
    "cooldown": 5,
    "id": "BIT-604",
    "name": "Glassdoor",
    "park_reason": "no_producer",
    "park_note": "fuel hook has no live Scouting producer. Person/LinkedIn enrichment not yet built. Re-activate only when a producer writes this hook to targets. Option A \u2014 June 2026.",
    "status": "parked",
    "family": "dossier",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-605",
    "name": "The Alumni",
    "status": "parked",
    "park_reason": "no_producer",
    "fuel_hooks": [],
    "cooldown": 4,
    "family": "dossier",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-606",
    "name": "The Relocator",
    "status": "parked",
    "park_reason": "no_producer",
    "fuel_hooks": [],
    "cooldown": 4,
    "family": "dossier",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "fuel_hooks": [],
    "cooldown": 5,
    "id": "BIT-607",
    "name": "Open To Work",
    "park_reason": "no_producer",
    "park_note": "fuel hook has no live Scouting producer. Person/LinkedIn enrichment not yet built. Re-activate only when a producer writes this hook to targets. Option A \u2014 June 2026.",
    "status": "parked",
    "family": "dossier",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-608",
    "name": "The Headline",
    "status": "parked",
    "park_reason": "no_producer",
    "fuel_hooks": [],
    "cooldown": 3,
    "family": "dossier",
    "absurdity": 1,
    "archetypes": "universal"
  },
  {
    "intensity": 0.4,
    "cooldown": 6,
    "id": "BIT-701",
    "name": "The Callback Hook",
    "trigger": "call_phase_late",
    "status": "active",
    "family": "death_blow",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-702",
    "name": "The Guilt Pivot",
    "intensity": 0.5,
    "cooldown": 6,
    "trigger": "call_phase_late",
    "status": "active",
    "family": "death_blow",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-703",
    "name": "The Confused Recap",
    "intensity": 0.6,
    "cooldown": 6,
    "trigger": "call_phase_late",
    "status": "active",
    "family": "death_blow",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-704",
    "name": "The Colleague Pull",
    "status": "active",
    "cooldown": 6,
    "intensity": 0.5,
    "trigger": "call_phase_late",
    "family": "death_blow",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-705",
    "name": "The Send-Off",
    "intensity": 0.3,
    "cooldown": 6,
    "trigger": "call_phase_late",
    "status": "active",
    "family": "death_blow",
    "absurdity": 2,
    "vocal_tag": "excited",
    "archetypes": "universal"
  },
  {
    "id": "BIT-901",
    "name": "The Sound-Flub Open",
    "lane": "gag",
    "phase_pref": "opening",
    "cooldown": 999,
    "trigger": "call_turn_1",
    "status": "active",
    "max_fires_per_call": 1,
    "family": "environment",
    "absurdity": 2,
    "vocal_tag": "neutral",
    "category": "900s \u2014 Opener",
    "archetypes": "universal"
  },
  {
    "id": "BIT-902",
    "name": "The Weather Remark",
    "status": "active",
    "family": "structural",
    "pool": "early",
    "trigger": "call_turn_1",
    "cooldown": 999,
    "max_fires_per_call": 1,
    "absurdity": 2,
    "vocal_tag": "content",
    "category": "900s \u2014 Opener",
    "archetypes": "universal"
  },
  {
    "id": "BIT-903",
    "name": "The Back-To-Back",
    "status": "active",
    "family": "structural",
    "pool": "early",
    "trigger": "call_turn_1",
    "cooldown": 999,
    "max_fires_per_call": 1,
    "absurdity": 2,
    "vocal_tag": "calm",
    "category": "900s \u2014 Opener",
    "archetypes": "universal"
  },
  {
    "id": "BIT-904",
    "name": "The Room Observation",
    "status": "active",
    "family": "structural",
    "pool": "early",
    "trigger": "call_turn_1",
    "cooldown": 999,
    "max_fires_per_call": 1,
    "absurdity": 2,
    "vocal_tag": "content",
    "category": "900s \u2014 Opener",
    "archetypes": "universal"
  },
  {
    "id": "BIT-905",
    "name": "The Punctuality",
    "status": "active",
    "cooldown": 999,
    "trigger": "call_turn_1",
    "family": "structural",
    "absurdity": 2,
    "vocal_tag": "content",
    "pool": "early",
    "max_fires_per_call": 1,
    "archetypes": "universal"
  },
  {
    "id": "BIT-330",
    "name": "The Dishwasher",
    "status": "active",
    "family": "environment",
    "pool": "none",
    "trigger": "none",
    "cooldown": 6,
    "max_fires_per_call": 1,
    "absurdity": 2,
    "vocal_tag": "content",
    "channel": "audio",
    "sound_markers": [
      "DISHWASHER_BG",
      "DISHWASHER_BG_STOP"
    ],
    "archetypes": "universal"
  },
  {
    "id": "BIT-331",
    "name": "The Thunderstorm",
    "status": "active",
    "family": "environment",
    "pool": "none",
    "trigger": "none",
    "cooldown": 6,
    "max_fires_per_call": 1,
    "absurdity": 2,
    "vocal_tag": "content",
    "channel": "audio",
    "sound_markers": [
      "THUNDER_BG",
      "THUNDER_BG_STOP"
    ],
    "archetypes": "universal"
  },
  {
    "id": "BIT-332",
    "name": "The Dump Truck",
    "status": "active",
    "family": "environment",
    "pool": "none",
    "trigger": "none",
    "cooldown": 6,
    "max_fires_per_call": 2,
    "absurdity": 2,
    "vocal_tag": "neutral",
    "channel": "audio",
    "sound_markers": [
      "DUMP_TRUCK_BG",
      "DUMP_TRUCK_BG_STOP"
    ],
    "archetypes": "universal"
  },
  {
    "id": "BIT-333",
    "name": "The Plane Overhead",
    "status": "active",
    "family": "environment",
    "pool": "none",
    "trigger": "none",
    "cooldown": 7,
    "max_fires_per_call": 2,
    "absurdity": 2,
    "vocal_tag": "content",
    "channel": "audio",
    "sound_markers": [
      "TAKEOFF_BG",
      "TAKEOFF_BG_STOP"
    ],
    "rung_spacing": {
      "min_between": 7
    },
    "archetypes": "universal"
  },
  {
    "id": "BIT-334",
    "name": "The Due Diligence",
    "status": "active",
    "family": "structural",
    "pool": "middle",
    "trigger": "caller_presenting",
    "cooldown": 5,
    "max_fires_per_call": 1,
    "absurdity": 3,
    "vocal_tag": "mysterious",
    "channel": "audio",
    "requires_context": "spammer has described their product, technology, or industry in specific terms",
    "archetypes": "universal"
  }
];
