#!/usr/bin/env node
/**
 * SpamViking — Bits Export Script
 * 
 * Regenerates _bits_registry.js and _bits_directives.js from source files.
 * Run after any edit to SpamViking_BitsRegistry.json or _bits_directives_source.js
 * 
 * Usage:
 *   node export_bits.js
 * 
 * Inputs:
 *   SpamViking_BitsRegistry.json  — registry source (edit this, not the .js)
 *   _bits_directives.js           — directive source (edit this directly)
 * 
 * Outputs:
 *   _bits_registry.js             — deploy to api/_bits_registry.js
 *   _bits_directives.js           — deploy to api/compiler/_bits_directives.js
 * 
 * The script validates both files before writing. If validation fails,
 * nothing is written and the error is reported.
 */

const fs = require('fs');
const path = require('path');

const REGISTRY_SOURCE = 'SpamViking_BitsRegistry.json';
const DIRECTIVES_FILE = '_bits_directives.js';
const REGISTRY_OUT    = '_bits_registry.js';

// ─── 1. Load and validate registry JSON ───────────────────────────────────────

let bits;
try {
  const raw = fs.readFileSync(REGISTRY_SOURCE, 'utf8');
  bits = JSON.parse(raw);
} catch (e) {
  console.error(`[FAIL] Could not parse ${REGISTRY_SOURCE}: ${e.message}`);
  process.exit(1);
}

if (!Array.isArray(bits) || bits.length === 0) {
  console.error(`[FAIL] ${REGISTRY_SOURCE} must be a non-empty array`);
  process.exit(1);
}

// Required fields check
const REQUIRED = ['id', 'name', 'status', 'cooldown'];
const errors = [];
const seenIds = new Set();

for (const b of bits) {
  for (const f of REQUIRED) {
    if (b[f] === undefined) errors.push(`${b.id ?? '?'}: missing required field "${f}"`);
  }
  if (b.id) {
    if (seenIds.has(b.id)) errors.push(`Duplicate id: ${b.id}`);
    seenIds.add(b.id);
  }
  if (b.status && !['active','parked','retired'].includes(b.status)) {
    errors.push(`${b.id}: invalid status "${b.status}"`);
  }
  // Warn on stale fields
  if (b.gear) errors.push(`${b.id}: stale "gear" field found — remove it`);
}

if (errors.length) {
  console.error('[FAIL] Registry validation errors:');
  errors.forEach(e => console.error('  ' + e));
  process.exit(1);
}

console.log(`[OK] Registry: ${bits.length} entries, ${bits.filter(b=>b.status==='active').length} active`);

// ─── 2. Write _bits_registry.js ───────────────────────────────────────────────

const registryOut = [
  '// SpamViking — Bits Registry',
  '// AUTO-GENERATED by export_bits.js — do not hand-edit',
  `// Source: ${REGISTRY_SOURCE}`,
  `// Generated: ${new Date().toISOString()}`,
  '',
  `export const BITS = ${JSON.stringify(bits, null, 2)};`,
  '',
].join('\n');

fs.writeFileSync(REGISTRY_OUT, registryOut, 'utf8');
console.log(`[OK] Written: ${REGISTRY_OUT}`);

// ─── 3. Validate _bits_directives.js ─────────────────────────────────────────

const directiveSrc = fs.readFileSync(DIRECTIVES_FILE, 'utf8');

// Extract the export default object
const defaultMatch = directiveSrc.match(/export default \{([\s\S]*)\};?\s*$/);
if (!defaultMatch) {
  console.error('[FAIL] _bits_directives.js: could not find "export default {..." block');
  process.exit(1);
}

// Find all bit keys declared
const keyMatches = [...directiveSrc.matchAll(/"(BIT-[0-9]+[a-z]?)"\s*:/g)];
const directiveIds = new Set(keyMatches.map(m => m[1]));

// Check every active bit has a directive
const activeBits = bits.filter(b => b.status === 'active');
const missingDirectives = activeBits.filter(b => !directiveIds.has(b.id));
const orphanDirectives = [...directiveIds].filter(id => !seenIds.has(id));

if (missingDirectives.length) {
  console.warn(`[WARN] Active bits with no directive (${missingDirectives.length}):`);
  missingDirectives.forEach(b => console.warn(`  ${b.id} — ${b.name}`));
}
if (orphanDirectives.length) {
  console.warn(`[WARN] Directives with no registry entry (${orphanDirectives.length}):`);
  orphanDirectives.forEach(id => console.warn(`  ${id}`));
}

// Check for missing commas between entries (the reported bug)
const commaErrors = [];
const entryPattern = /(`)\s*\n\n("BIT-)/g;
let cm;
while ((cm = entryPattern.exec(directiveSrc)) !== null) {
  const lineNo = directiveSrc.slice(0, cm.index).split('\n').length;
  commaErrors.push(`Line ~${lineNo}: missing comma between entries`);
}

if (commaErrors.length) {
  console.error('[FAIL] _bits_directives.js comma errors:');
  commaErrors.forEach(e => console.error('  ' + e));
  process.exit(1);
}

console.log(`[OK] Directives: ${directiveIds.size} entries, no comma errors`);
console.log('[OK] Export complete — deploy both output files to Vercel');
